name: ServiceNow Manual Deploy

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Where to deploy?"
        required: true
        type: choice
        options:
          - uat
          - prod

jobs:
  deploy:
    name: Deploy to ${{ inputs.target_env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply changes to UAT
        if: ${{ inputs.target_env == 'uat' }}
        uses: ServiceNow/sncicd-apply-changes@1.2.1
        env:
          snowUsername: ${{ secrets.SN_TEST_USERNAME }}
          snowPassword: ${{ secrets.SN_TEST_PASSWORD }}
          snowSourceInstance: ${{ secrets.NOW_TEST_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}

      - name: Apply changes to PROD
        if: ${{ inputs.target_env == 'prod' }}
        uses: ServiceNow/sncicd-apply-changes@1.2.1
        env:
          snowUsername: ${{ secrets.SN_PROD_USERNAME }}
          snowPassword: ${{ secrets.SN_PROD_PASSWORD }}
          snowSourceInstance: ${{ secrets.NOW_PROD_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
